name: Mobile CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ios-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: npm install

      - name: Test iOS
        env:
          BROWSERSTACK_USER: ${{ secrets.BS_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BS_KEY }}
        run: npx wdio config/wdio.ios.bs.conf.js --spec test/specs/ios/demotest.bs.spec.js

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ios-logs
          path: logs

  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: npm install

      - name: Test Android
        env:
          BROWSERSTACK_USER: ${{ secrets.BS_USER }}
          BROWSERSTACK_KEY: ${{ secrets.BS_KEY }}
        run: npx wdio config/wdio.android.bs.conf.js --spec test/specs/android/add-note-screen.spec.js

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: android-logs
          path: logs
